[package]
name = "manatee-runtime"
version = "0.1.0"
description = "API endpoint for TEEs to communicate with Trichechus."
authors = ["The Chromium OS Authors"]
edition = "2018"

[[bin]]
name = "demo_app"
path = "src/demo-app.rs"

[dependencies]
libsirenia = { path = "../libsirenia" } # provided by ebuild
serde = { version = "1.0.114", features = ["derive"] }
sync = { path = "../../../platform/crosvm/common/sync" } # provided by ebuild
sys_util = { path = "../../../platform/crosvm/common/sys_util" } # provided by ebuild
