# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Schema can be found at: platform/dev/test/gtest/gtest_schema.yaml
---
author: "ChromiumOS Authors"
name: "QuickSettingsIntegrationTest"
harness: "crosier"
category: "integration"
owners:
  - email: "jamescook@chromium.org"
  - email: "brettw@chromium.org"
  - email: "chromeos-sw-engprod@google.com"
hw_agnostic: True
criteria: |
  Testing the OS Settings system web app.
cases:
  - id: "OpenOsSettings"
    tags: ["crosier:crosierdemosuite"]
  - id: "ManagedDeviceInfo"
    tags: ["crosier:crosierdemosuite"]
...
